---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensemble
  labels:
    app: ensemble
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ensemble
      version: v1
  template:
    metadata:
      labels:
        app: ensemble
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: ensemble
          imagePullPolicy: "IfNotPresent"
          image: rdsea/ensemble
          ports:
            - containerPort: 5011
          env:
            - name: MANUAL_TRACING
              value: "true"
            - name: OTEL_ENDPOINT
              value: "http://jaeger-collector.observe.svc.cluster.local:4318/v1/traces"
            - name: SEND_TO_QUEUE
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: ensemble-service
spec:
  ports:
    - port: 5011
      targetPort: 5011
  selector:
    app: ensemble
